In [9]:
import pandas as pd

In [10]:
df_201801 = "Resources/201801_tripdata.csv"
df1_201801 = pd.read_csv(df_201801)
len(df1_201801)

718994

In [11]:
df_201802 = "Resources/201802_tripdata.csv"
df2_201802 = pd.read_csv(df_201802)
len(df2_201802)

843114

In [12]:
df_201803 = "Resources/201803_tripdata.csv"
df3_201803 = pd.read_csv(df_201803)
len(df3_201803)

976672

In [10]:
df_201804 = "Resources/201804_tripdata.csv"
df4_201804 = pd.read_csv(df_201804)
len(df4_201804)

1307543

In [3]:
df_201805 = "Resources/201805_tripdata.csv"
df5_201805 = pd.read_csv(df_201805)
len(df5_201805)

1824710

In [4]:
df_201806 = "Resources/201806_tripdata.csv"
df6_201806 = pd.read_csv(df_201806)
len(df6_201806)

1953103

In [5]:
df_201807 = "Resources/201807_tripdata.csv"
df7_201807 = pd.read_csv(df_201807)
len(df7_201807)

1913625

In [15]:
df_201808 = "Resources/201808_tripdata.csv"
df8_201808 = pd.read_csv(df_201808)
len(df8_201808)

44432

In [16]:
df_201809 = "Resources/201809_tripdata.csv"
df9_201809 = pd.read_csv(df_201809)
len(df9_201809)

39022

In [17]:
df_201810 = "Resources/201810_tripdata.csv"
df10_201810 = pd.read_csv(df_201810)
len(df10_201810)

39138

In [25]:
df_201811 = "Resources/201811_tripdata.csv"
df11_201811 = pd.read_csv(df_201811)
len(df11_201811)

24910

In [23]:
bikedata_201810 = "201810_tripdata.csv"
# df = pd.read_csv(bikedata_2018)
bikedata_201810_df = pd.read_csv(bikedata_201810)
len(bikedata_201810_df)
# bikedata_201810_df.head()

39138

In [24]:
bikedata_201811 = "201811_tripdata.csv"
# df = pd.read_csv(bikedata_2018)
bikedata_201811_df = pd.read_csv(bikedata_201811)
len(bikedata_201811_df)
# bikedata_201811_df.count()

24910

In [27]:
bikedata_201812 = "201812_tripdata.csv"
# df = pd.read_csv(bikedata_201812)
bikedata_201812_df = pd.read_csv(bikedata_201812)
len(bikedata_201812_df)
bikedata_201812_df.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,170,2018-12-01 00:03:53.3860,2018-12-01 00:06:43.7160,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26261,Subscriber,1975,1
1,172,2018-12-01 00:47:13.7340,2018-12-01 00:50:05.8160,3183,Exchange Place,40.716247,-74.033459,3481,York St,40.716490,-74.041050,26175,Subscriber,1988,1

In [13]:
bikedata_201712 = "201712_bikedata.csv"
bikedata_201712_df = pd.read_csv(bikedata_201712)
len(bikedata_201712_df)
# bikedata_201712_df['Age'] = 2017 - bikedata_201712_df['birth year'];
# bikedata_201712_df.head(2)

15898

# summer and winter datasets

In [8]:
summer_data = pd.concat([df5_201805,df6_201806,
                        df7_201807])
len(summer_data)

5691438

In [7]:
summer_data.to_csv('summer_data.csv', sep = ',')

In [16]:
winter_data = pd.concat([bikedata_201712_df,df1_201801,df2_201802])
len(winter_data)

1578006

In [17]:
winter_data.to_csv('winter_data.csv', sep = ',')

# combined data from dec2017 to dec2018

In [47]:
# combine bike data from dec 2017 to dec 2018
data_2018=pd.concat([df1_201801,df2_201802,df3_201803,df4_201804,df5_201805,df6_201806,
                        df7_201807,df8_201808,df9_201809,df10_201810,df11_201811,bikedata_201812_df])
len(data_2018)

9705468

In [ ]:
data_2018.head()

In [49]:
data_2018['Age'] = 2018 - data_2018['birth year'];
data_2018

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Age
0,970,2018-01-01 13:50:57.4340,2018-01-01 14:07:08.1860,72,W 52 St & 11 Ave,40.767272,-73.993929,505,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1,26
1,723,2018-01-01 15:33:30.1820,2018-01-01 15:45:33.3410,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1,49
2,496,2018-01-01 15:39:18.3370,2018-01-01 15:47:35.1720,72,W 52 St & 11 Ave,40.767272,-73.993929,525,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1,62
3,306,2018-01-01 15:40:13.3720,2018-01-01 15:45:20.1910,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1,44
4,306,2018-01-01 18:14:51.5680,2018-01-01 18:19:57.6420,72,W 52 St & 11 Ave,40.767272,-73.993929,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1,26
5,1602,2018-01-01 21:31:54.1920,2018-01-01 21:58:36.3530,72,W 52 St & 11 Ave,40.767272,-73.993929,482,W 15 St & 7 Ave,40.739355,-73.999318,30106,Subscriber,1968,1,50
6,722,2018-01-02 07:54:53.6460,2018-01-02 08:06:55.8720,72,W 52 St & 11 Ave,40.767272,-73.993929,228,E 48 St & 3 Ave,40.754601,-73.971879,32059,Subscriber,1978,1,40
7,434,2018-01-02 08:06:14.3310,2018-01-02 08:13:28.7670,72,W 52 St & 11 Ave,40.767272,-73.993929,173,Broadway & W 49 St,40.760683,-73.984527,30525,Subscriber,1983,1,35
8,366,2018-01-02 08:10:15.2550,2018-01-02 08:16:21.8960,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,27439,Subscriber,1974,1,44
9,324,2018-01-02 08:13:30.8960,2018-01-02 08:18:55.1200,72,W 52 St & 11 Ave,40.767272,-73.993929,450,W 49 St & 8 Ave,40.762272,-73.987882,30892,Subscriber,1947,1,71
10,1155,2018-01-02 09:15:29.9050,2018-01-02 09:34:45.0200,72,W 52 St & 11 Ave,40.767272,-73.993929,347,Greenwich St & W Houston St,40.728846,-74.008591,31591,Subscriber,1982,1,36
11,1200,2018-01-02 10:23:18.8800,2018-01-02 10:43:18.9110,72,W 52 St & 11 Ave,40.767272,-73.993929,127,Barrow St & Hudson St,40.731724,-74.006744,30257,Subscriber,1974,1,44
12,732,2018-01-02 11:52:37.5540,2018-01-02 12:04:49.8800,72,W 52 St & 11 Ave,40.767272,-73.993929,3635,W 36 St & 9 Ave,40.754623,-73.995168,32649,Subscriber,1969,1,49
13,600,2018-01-02 12:20:57.0070,2018-01-02 12:30:57.0180,72,W 52 St & 11 Ave,40.767272,-73.993929,457,Broadway & W 58 St,40.766953,-73.981693,26964,Subscriber,1991,1,27
14,1058,2018-01-02 13:28:46.1540,2018-01-02 13:46:24.3070,72,W 52 St & 11 Ave,40.767272,-73.993929,523,W 38 St & 8 Ave,40.754666,-73.991382,32617,Subscriber,1947,1,71
15,256,2018-01-02 13:54:11.6460,2018-01-02 13:58:28.1980,72,W 52 St & 11 Ave,40.767272,-73.993929,514,12 Ave & W 40 St,40.760875,-74.002777,31095,Subscriber,1978,1,40
16,318,2018-01-02 13:55:11.9200,2018-01-02 14:00:29.9410,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,31182,Subscriber,1963,1,55
17,694,2018-01-02 14:27:49.6230,2018-01-02 14:39:24.1270,72,W 52 St & 11 Ave,40.767272,-73.993929,484,W 44 St & 5 Ave,40.755003,-73.980144,32375,Subscriber,1967,1,51
18,604,2018-01-02 15:04:41.3810,2018-01-02 15:14:45.7090,72,W 52 St & 11 Ave,40.767272,-73.993929,3635,W 36 St & 9 Ave,40.754623,-73.995168,32505,Subscriber,1964,1,54
19,724,2018-01-02 15:25:00.5410,2018-01-02 15:37:05.3230,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,19512,Subscriber,1965,1,53
20,395,2018-01-02 15:37:55.9310,2018-01-02 15:44:31.0550,72,W 52 St & 11 Ave,40.767272,-73.993929,514,12 Ave & W 40 St,40.760875,-74.002777,17881,Subscriber,1956,1,62
21,520,2018-01-02 16:09:21.1800,2018-01-02 16:18:02.0510,72,W 52 St & 11 Ave,40.767272,-73.993929,500,Broadway & W 51 St,40.762288,-73.983362,31426,Customer,1969,0,49
22,430,2018-01-02 16:10:59.3790,2018-01-02 16:18:10.0110,72,W 52 St & 11 Ave,40.767272,-73.993929,500,Broadway & W 51 St,40.762288,-73.983362,32349,Customer,1969,0,49
23,842,2018-01-02 16:34:16.2920,2018-01-02 16:48:18.6180,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,31019,Subscriber,1978,1,40
24,243,2018-01-02 16:36:12.6120,2018-01-02 16:40:15.7660,72,W 52 St & 11 Ave,40.767272,-73.993929,479,9 Ave & W 45 St,40.760193,-73.991255,29984,Subscriber,1973,1,45
25,705,2018-01-02 16:36:14.3160,2018-01-02 16:47:59.7340,72,W 52 St & 11 Ave,40.767272,-73.993929,477,W 41 St & 8 Ave,40.756405,-73.990026,20922,Subscriber,1992,1,26
26,1163,2018-01-02 16:43:09.9290,2018-01-02 17:02:33.2530,72,W 52 St & 11 Ave,40.767272,-73.993929,3466,W 45 St & 6 Ave (OLD),40.756687,-73.982577,33277,Subscriber,1974,1,44
27,680,2018-01-02 16:58:34.7080,2018-01-02 17:09:55.0030,72,W 52 St & 11 Ave,40.767272,-73.993929,490,8 Ave & W 33 St,40.751551,-73.993934,16425,Subscriber,1964,1,54
28,634,2018-01-02 17:04:25.6190,2018-01-02 17:14:59.7750,72,W 52 St & 11 Ave,40.767272,-73.993929,484,W 44 St & 5 Ave,40.755003,-73.980144,28382,Subscriber,1977,1,41
29,782,2018-01-02 17:13:04.4750,2018-01-02 17:26:06.8250,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,30649,Subscriber,1982,1,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20175,747,2018-12-10 20:33:10.0440,2018-12-10 20:45:37.2790,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29519,Subscriber,1958,1,60
20176,1124,2018-12-11 06:19:14.0610,2018-12-11 06:37:58.7960,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29657,Subscriber,1977,1,41
20177,648,2018-12-11 12:01:04.1040,2018-12-11 12:11:52.9080,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26287,Subscriber,1994,1,24
20178,575,2018-12-11 17:46:56.6360,2018-12-11 17:56:31.6520,3694,Jackson Square,40.711130,-74.078900,3191,Union St,40.718211,-74.083639,29239,Subscriber,1958,1,60
20179,961,2018-12-12 06:19:04.3900,2018-12-12 06:35:05.8390,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26247,Subscriber,1977,1,41
20180,2058,2018-12-12 09:09:44.0380,2018-12-12 09:44:02.7900,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29641,Subscriber,1957,1,61
20181,640,2018-12-12 11:54:45.5290,2018-12-12 12:05:25.7630,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29641,Subscriber,1994,1,24
20182,934,2018-12-13 06:16:06.7510,2018-12-13 06:31:41.2170,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29681,Subscriber,1977,1,41
20183,703,2018-12-13 12:17:13.6280,2018-12-13 12:28:57.2350,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26190,Subscriber,1994,1,24
20184,936,2018-12-14 06:10:18.5060,2018-12-14 06:25:54.6120,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26155,Subscriber,1977,1,41
20185,668,2018-12-14 12:34:01.0310,2018-12-14 12:45:09.6550,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26312,Subscriber,1994,1,24
20186,645,2018-12-15 13:31:59.3590,2018-12-15 13:42:45.2030,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29224,Subscriber,1994,1,24
20187,1396,2018-12-15 16:28:38.1250,2018-12-15 16:51:54.9460,3694,Jackson Square,40.711130,-74.078900,3279,Dixon Mills,40.721630,-74.049968,29126,Subscriber,1988,2,30
20188,649,2018-12-16 11:55:07.8820,2018-12-16 12:05:57.4260,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29658,Subscriber,1994,1,24
20189,984,2018-12-17 06:26:18.2690,2018-12-17 06:42:42.9330,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26251,Subscriber,1977,1,41
20190,687,2018-12-17 12:18:47.1320,2018-12-17 12:30:14.5090,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29535,Subscriber,1994,1,24
20191,726,2018-12-17 17:38:45.4430,2018-12-17 17:50:52.4320,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29276,Subscriber,1973,2,45
20192,1041,2018-12-18 06:21:57.7450,2018-12-18 06:39:19.7440,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29221,Subscriber,1977,1,41
20193,654,2018-12-18 12:12:40.2980,2018-12-18 12:23:34.4020,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29300,Subscriber,1994,1,24
20194,1015,2018-12-19 06:15:11.2330,2018-12-19 06:32:06.2450,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26220,Subscriber,1977,1,41
20195,667,2018-12-19 11:39:50.4270,2018-12-19 11:50:58.2750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29299,Subscriber,1994,1,24
20196,687,2018-12-20 13:28:39.0590,2018-12-20 13:40:06.6410,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29258,Subscriber,1994,1,24
20197,625,2018-12-21 12:05:04.3890,2018-12-21 12:15:29.5930,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29664,Subscriber,1994,1,24
20198,826,2018-12-21 16:34:37.2330,2018-12-21 16:48:24.0150,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,26306,Subscriber,1991,1,27
20199,640,2018-12-22 10:27:40.6590,2018-12-22 10:38:21.4170,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26298,Subscriber,1994,1,24
20200,1081,2018-12-22 11:51:46.0600,2018-12-22 12:09:47.4730,3694,Jackson Square,40.711130,-74.078900,3269,Brunswick & 6th,40.726012,-74.050389,29586,Subscriber,1993,1,25
20201,344,2018-12-25 21:40:09.8660,2018-12-25 21:45:54.2670,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26241,Subscriber,1983,2,35
20202,1233,2018-12-29 12:55:45.9690,2018-12-29 13:16:19.5960,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29294,Subscriber,1988,1,30
20203,1057,2018-12-30 15:32:09.3320,2018-12-30 15:49:46.3510,3694,Jackson Square,40.711130,-74.078900,3213,Van Vorst Park,40.718489,-74.047727,29475,Subscriber,1991,2,27
20204,301,2018-12-31 16:34:11.9340,2018-12-31 16:39:13.8340,3694,Jackson Square,40.711130,-74.078900,3277,Communipaw & Berry Lane,40.714358,-74.066611,26270,Subscriber,1991,1,27

In [52]:
data_2018_17 = pd.concat([bikedata_201712_df,data_2018])
len(data_2018_17)

9721366

In [53]:
data_2018_17.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Age
0,452,2017-12-01 00:00:59,2017-12-01 00:08:32,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,29607,Subscriber,1988.0,1,29.0
1,159,2017-12-01 00:04:42,2017-12-01 00:07:21,3187,Warren St,40.721124,-74.038051,3186,Grove St PATH,40.719586,-74.043117,26269,Subscriber,1992.0,1,25.0

In [54]:
data_2018_17.to_csv('data_2017_18.csv', sep = ',')

# Groupby on station name

In [52]:

bikedata_201712_df1=bikedata_201712_df.loc[bikedata_201712_df['start station name']=='Hamilton Park']
bikedata_201712_df1.loc[bikedata_201712_df1['end station name']=='5 Corners Library']

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
951,763,2017-12-01 21:34:40,2017-12-01 21:47:24,3203,Hamilton Park,40.727596,-74.044247,3220,5 Corners Library,40.734961,-74.059503,31903,Subscriber,1960.0,1
2997,811,2017-12-04 20:49:16,2017-12-04 21:02:47,3203,Hamilton Park,40.727596,-74.044247,3220,5 Corners Library,40.734961,-74.059503,31873,Subscriber,1960.0,1
13536,1008,2017-12-22 15:21:07,2017-12-22 15:37:56,3203,Hamilton Park,40.727596,-74.044247,3220,5 Corners Library,40.734961,-74.059503,29597,Subscriber,1960.0,1

In [47]:
trips17_df = bikedata_201712_df.groupby(['start station name','end station name']).size().reset_index(name = 'Number of Trips')
# print(trips17_df[trips17_df['start station name']=='Hamilton Park']['Number of Trips'])
trips17_df.loc[trips17_df['start station name']=='Hamilton Park']

    start station name       end station name  Number of Trips
397      Hamilton Park      5 Corners Library                3
398      Hamilton Park  Baldwin at Montgomery                1
399      Hamilton Park        Brunswick & 6th                7
400      Hamilton Park           Brunswick St                3
401      Hamilton Park        Christ Hospital                1
402      Hamilton Park              City Hall               30
403      Hamilton Park         Columbus Drive               11
404      Hamilton Park            Dixon Mills                6
405      Hamilton Park       Essex Light Rail                9
406      Hamilton Park         Exchange Place               39
407      Hamilton Park          Grove St PATH              560
408      Hamilton Park          Hamilton Park               42
409      Hamilton Park             Harborside               47
410      Hamilton Park       Heights Elevator                2
411      Hamilton Park                Hilltop                2
412      Hamilton Park      JC Medical Center                3
413      Hamilton Park           Jersey & 3rd               39
414      Hamilton Park        Jersey & 6th St               17
415      Hamilton Park           Lincoln Park                1
416      Hamilton Park           Manila & 1st               82
417      Hamilton Park       Marin Light Rail                2
418      Hamilton Park        McGinley Square                1
419      Hamilton Park       Monmouth and 6th                2
420      Hamilton Park             Newark Ave               69
421      Hamilton Park           Newport PATH              164
422      Hamilton Park           Newport Pkwy               19
423      Hamilton Park            Oakland Ave                1
424      Hamilton Park            Paulus Hook               16
425      Hamilton Park         Riverview Park                2
426      Hamilton Park                Sip Ave                1
427      Hamilton Park         Van Vorst Park               18
428      Hamilton Park              Warren St                7
429      Hamilton Park          Washington St                6
430      Hamilton Park                York St                1

In [10]:
# data for dec 2017 and dec 2018
newdata_2018_17=pd.concat([bikedata_201812_df, bikedata_201712_df])

In [29]:
# combine bike data from dec 2017 to dec 2018
data_2018_17=pd.concat([bikedata_201712_df,df1_201801,df2_201802,df3_201803,df4_201804,df5_201805,df6_201806,
                        df7_201807,df8_201808,df9_201809,df10_201810,df11_201811,bikedata_201812_df])

In [33]:
newdata_2018_17.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
15893,972,2017-12-31 21:54:12,2017-12-31 22:10:25,3191,Union St,40.718211,-74.083639,3186,Grove St PATH,40.719586,-74.043117,29644,Subscriber,1987.0,2
15894,382,2017-12-31 22:10:18,2017-12-31 22:16:41,3280,Astor Place,40.719282,-74.071262,3268,Lafayette Park,40.713464,-74.062859,31799,Subscriber,1994.0,1
15895,93,2017-12-31 22:55:10,2017-12-31 22:56:43,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717733,-74.043845,31920,Subscriber,1957.0,1
15896,186,2017-12-31 23:20:54,2017-12-31 23:24:00,3270,Jersey & 6th St,40.725289,-74.045572,3211,Newark Ave,40.721525,-74.046305,31925,Subscriber,1964.0,1
15897,422,2017-12-31 23:33:55,2017-12-31 23:40:57,3195,Sip Ave,40.730743,-74.063784,3280,Astor Place,40.719282,-74.071262,31709,Subscriber,1979.0,1

In [14]:
newdata_2018_17.to_csv('newdata_2018_17.csv', sep = ',')

In [57]:
trips_df = newdata_2018_17.groupby(['start station name','end station name']).size().reset_index(name = 'Number of Trips')
trips_df.loc[trips_df['start station name']=='Hamilton Park']

    start station name       end station name  Number of Trips
598      Hamilton Park      5 Corners Library                4
599      Hamilton Park  Baldwin at Montgomery                1
600      Hamilton Park        Brunswick & 6th               14
601      Hamilton Park           Brunswick St               28
602      Hamilton Park        Christ Hospital                2
603      Hamilton Park              City Hall               66
604      Hamilton Park         Columbus Drive               25
605      Hamilton Park            Dixon Mills                7
606      Hamilton Park       Essex Light Rail               11
607      Hamilton Park         Exchange Place               56
608      Hamilton Park               Grand St               10
609      Hamilton Park          Grove St PATH             1034
610      Hamilton Park          Hamilton Park               69
611      Hamilton Park             Harborside              101
612      Hamilton Park       Heights Elevator               13
613      Hamilton Park                Hilltop                2
614      Hamilton Park      JC Medical Center               20
615      Hamilton Park           Jersey & 3rd               90
616      Hamilton Park        Jersey & 6th St               31
617      Hamilton Park     Liberty Light Rail                4
618      Hamilton Park           Lincoln Park                1
619      Hamilton Park           Manila & 1st              218
620      Hamilton Park       Marin Light Rail               12
621      Hamilton Park        McGinley Square                1
622      Hamilton Park       Monmouth and 6th                8
623      Hamilton Park          Montgomery St                9
624      Hamilton Park             Newark Ave              158
625      Hamilton Park           Newport PATH              251
626      Hamilton Park           Newport Pkwy               30
627      Hamilton Park            Oakland Ave                1
628      Hamilton Park            Paulus Hook               33
629      Hamilton Park         Riverview Park                2
630      Hamilton Park                Sip Ave                4
631      Hamilton Park         Van Vorst Park               39
632      Hamilton Park              Warren St               22
633      Hamilton Park          Washington St               18
634      Hamilton Park                York St                4

In [25]:
trips_df_sort = trips_df.sort_values(["Number of Trips"], ascending=False)
trips_df_sort.head(2)

    start station name end station name  Number of Trips
609      Hamilton Park    Grove St PATH             1034
567      Grove St PATH    Hamilton Park              699

In [31]:
trips_df_sort['Route'] = trips_df_sort['start station name']+ " to " + trips_df_sort['end station name']
trips_df_sort

,start station name,end station name,Number of Trips,Route
609,Hamilton Park,Grove St PATH,1034,Hamilton Park to Grove St PATH
567,Grove St PATH,Hamilton Park,699,Grove St PATH to Hamilton Park
1194,Morris Canal,Exchange Place,539,Morris Canal to Exchange Place
834,Jersey & 6th St,Grove St PATH,509,Jersey & 6th St to Grove St PATH
464,Exchange Place,Morris Canal,472,Exchange Place to Morris Canal
141,Brunswick & 6th,Grove St PATH,449,Brunswick & 6th to Grove St PATH
382,Dixon Mills,Grove St PATH,411,Dixon Mills to Grove St PATH
1128,Monmouth and 6th,Grove St PATH,405,Monmouth and 6th to Grove St PATH
179,Brunswick St,Grove St PATH,397,Brunswick St to Grove St PATH
560,Grove St PATH,Dixon Mills,389,Grove St PATH to Dixon Mills
1111,McGinley Square,Sip Ave,384,McGinley Square to Sip Ave
1515,Sip Ave,McGinley Square,381,Sip Ave to McGinley Square
1563,Van Vorst Park,Grove St PATH,372,Van Vorst Park to Grove St PATH
552,Grove St PATH,Brunswick & 6th,349,Grove St PATH to Brunswick & 6th
1042,Marin Light Rail,Grove St PATH,342,Marin Light Rail to Grove St PATH
582,Grove St PATH,Monmouth and 6th,339,Grove St PATH to Monmouth and 6th
580,Grove St PATH,Marin Light Rail,329,Grove St PATH to Marin Light Rail
553,Grove St PATH,Brunswick St,326,Grove St PATH to Brunswick St
574,Grove St PATH,Jersey & 6th St,297,Grove St PATH to Jersey & 6th St
59,Astor Place,Sip Ave,279,Astor Place to Sip Ave
1481,Sip Ave,Astor Place,278,Sip Ave to Astor Place
1279,Newport PATH,Hamilton Park,257,Newport PATH to Hamilton Park
625,Hamilton Park,Newport PATH,251,Hamilton Park to Newport PATH
1482,Sip Ave,Baldwin at Montgomery,248,Sip Ave to Baldwin at Montgomery
594,Grove St PATH,Van Vorst Park,247,Grove St PATH to Van Vorst Park
1280,Newport PATH,Harborside,236,Newport PATH to Harborside
1298,Newport PATH,Newport Pkwy,235,Newport PATH to Newport Pkwy
411,Essex Light Rail,Exchange Place,226,Essex Light Rail to Exchange Place
1511,Sip Ave,Lincoln Park,225,Sip Ave to Lincoln Park
573,Grove St PATH,Jersey & 3rd,219,Grove St PATH to Jersey & 3rd
...,...,...,...,...
293,Columbus Drive,Brunswick & 6th,1,Columbus Drive to Brunswick & 6th
295,Columbus Drive,Christ Hospital,1,Columbus Drive to Christ Hospital
1204,Morris Canal,Lincoln Park,1,Morris Canal to Lincoln Park
1201,Morris Canal,Jersey & 3rd,1,Morris Canal to Jersey & 3rd
1199,Morris Canal,Heights Elevator,1,Morris Canal to Heights Elevator
309,Columbus Drive,Journal Square,1,Columbus Drive to Journal Square
1190,Morris Canal,Christ Hospital,1,Morris Canal to Christ Hospital
321,Columbus Drive,Oakland Ave,1,Columbus Drive to Oakland Ave
1183,Montgomery St,Sip Ave,1,Montgomery St to Sip Ave
1180,Montgomery St,Newport Pkwy,1,Montgomery St to Newport Pkwy
1169,Montgomery St,Jersey & 6th St,1,Montgomery St to Jersey & 6th St
328,Communipaw & Berry Lane,Baldwin at Montgomery,1,Communipaw & Berry Lane to Baldwin at Montgomery
329,Communipaw & Berry Lane,Bayside Park,1,Communipaw & Berry Lane to Bayside Park
333,Communipaw & Berry Lane,Exchange Place,1,Communipaw & Berry Lane to Exchange Place
1119,Monmouth and 6th,Bergen Ave,1,Monmouth and 6th to Bergen Ave
1154,Montgomery St,Brunswick & 6th,1,Montgomery St to Brunswick & 6th
1152,Monmouth and 6th,York St,1,Monmouth and 6th to York St
335,Communipaw & Berry Lane,JC Medical Center,1,Communipaw & Berry Lane to JC Medical Center
1147,Monmouth and 6th,Riverview Park,1,Monmouth and 6th to Riverview Park
1146,Monmouth and 6th,Pershing Field,1,Monmouth and 6th to Pershing Field
1144,Monmouth and 6th,Oakland Ave,1,Monmouth and 6th to Oakland Ave
1140,Monmouth and 6th,Morris Canal,1,Monmouth and 6th to Morris Canal
1137,Monmouth and 6th,Marin Light Rail,1,Monmouth and 6th to Marin Light Rail
338,Communipaw & Berry Lane,Jersey & 3rd,1,Communipaw & Berry Lane to Jersey & 3rd
340,Communipaw & Berry Lane,Liberty Light Rail,1,Communipaw & Berry Lane to Liberty Light Rail
341,Communipaw & Berry Lane,MLK Light Rail,1,Communipaw & Berry Lane to MLK Light Rail
342,Communipaw & Berry Lane,Manila & 1st,1,Communipaw & Berry Lane to Manila & 1st
343,Communipaw & Berry Lane,McGinley Square,1,Communipaw & Berry Lane to McGinley Square
1121,Monmouth and 6th,Brunswick St,1,Monmouth and 6th to Brunswick St
1163,Montgomery St,Grand St,1,Montgomery St to Grand St

In [32]:
trips_df_sort.to_csv('Popular_Trips_df.csv', sep = ',')